backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "produk"
    label: "Produk"
    folder: "content/produk"
    create: true
    fields:
      - { label: "Nama", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Gambar", name: "thumbnail", widget: "image" }
      - { label: "Deskripsi", name: "body", widget: "markdown" }
      - { label: "Link Shopee", name: "link", widget: "string" }

  - name: "artikel"
    label: "Artikel"
    folder: "content/artikel"
    create: true
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Konten", name: "body", widget: "markdown" }
      - { label: "Tampilkan Iklan?", name: "adsense", widget: "boolean", default: true }
