name: Sinkronisasi Artikel ke Firestore

on:
  push:
    paths:
      - 'content/artikel/**'
      - '.github/workflows/sync-artikel.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Tulis FIREBASE_KEY ke file
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" > serviceAccountKey.json

      - name: Jalankan sinkronisasi
        run: npm run sync
