name: Sinkronisasi Artikel ke Firestore

on:
  push:
    paths:
      - 'content/artikel/**'
      - '.github/workflows/sync-artikel.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Jalankan sinkronisasi
        run: npm run sync
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}

      - name: Debug FIREBASE_KEY
        run: echo "KEY LENGTH: ${#FIREBASE_KEY}"
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}

